//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamelessOld.Libraries.DB.Mikasa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NamelessOld.Libraries.DB.Mikasa.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the database..
        /// </summary>
        internal static string CanNotConnect {
            get {
                return ResourceManager.GetString("CanNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async transaction.
        /// </summary>
        internal static string CAPTION_ASYNC_TR {
            get {
                return ResourceManager.GetString("CAPTION_ASYNC_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background transaction.
        /// </summary>
        internal static string CAPTION_BG_TR {
            get {
                return ResourceManager.GetString("CAPTION_BG_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main thread transaction.
        /// </summary>
        internal static string CAPTION_MAIN_TR {
            get {
                return ResourceManager.GetString("CAPTION_MAIN_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection file &quot;{0}&quot;, can not be loaded.
        ///Because the file does not exist.
        /// </summary>
        internal static string ConnMising {
            get {
                return ResourceManager.GetString("ConnMising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Connection: {0}.
        /// </summary>
        internal static string ConnTitle {
            get {
                return ResourceManager.GetString("ConnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown connection error.
        /// </summary>
        internal static string ERR_CON_UNKNOWN {
            get {
                return ResourceManager.GetString("ERR_CON_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to database.
        /// </summary>
        internal static string ERR_CONN {
            get {
                return ResourceManager.GetString("ERR_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating the password or unlocking the database.
        /// </summary>
        internal static string ERR_LOCKING {
            get {
                return ResourceManager.GetString("ERR_LOCKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction was defined as a main thread transaction but is used as background worker transaction..
        /// </summary>
        internal static string ERR_TRAN_DEF_BG {
            get {
                return ResourceManager.GetString("ERR_TRAN_DEF_BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction was defined as a background worker transaction but is used as {0}..
        /// </summary>
        internal static string ERR_TRAN_DEF_MAIN {
            get {
                return ResourceManager.GetString("ERR_TRAN_DEF_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to database.
        /// </summary>
        internal static string MSG_CON {
            get {
                return ResourceManager.GetString("MSG_CON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error excecuting the transaction.
        /// </summary>
        internal static string TransactionError {
            get {
                return ResourceManager.GetString("TransactionError", resourceCulture);
            }
        }
    }
}
