//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaSoft.Riviera.Modulador.Bordeo.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaSoft.Riviera.Modulador.Bordeo.Assets.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el bloque &quot;{0}&quot; de la línea bordeo, en el directorio {1}..
        /// </summary>
        internal static string ERR_BORDEO_FILE_MISSING {
            get {
                return ResourceManager.GetString("ERR_BORDEO_FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código {0} no se encontró en la base de datos..
        /// </summary>
        internal static string ERR_CODE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_CODE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La base de datos de la línea Bordeo no se cargo en la aplicación..
        /// </summary>
        internal static string ERR_DB_NOT_READY {
            get {
                return ResourceManager.GetString("ERR_DB_NOT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear el bloque de bordeo &quot;{0}&quot;.
        /// </summary>
        internal static string ERR_LOADING_BLOCK {
            get {
                return ResourceManager.GetString("ERR_LOADING_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para {0} el objeto debe ser de la línea Bordeo..
        /// </summary>
        internal static string ERR_NOT_BORDERO {
            get {
                return ResourceManager.GetString("ERR_NOT_BORDERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor nominal proporcionado &quot;{0}&quot;, no es un tamaño de dibujo válido..
        /// </summary>
        internal static string ERR_UNKNOWN_DRAWING_SIZE {
            get {
                return ResourceManager.GetString("ERR_UNKNOWN_DRAWING_SIZE", resourceCulture);
            }
        }
    }
}
