//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaSoft.Riviera.OldModulador.Assets {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaSoft.Riviera.OldModulador.Assets.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La columna asociada no es válida para crear un tamaño de mampara.
        /// </summary>
        internal static string BAD_ROW_MAMPARA {
            get {
                return ResourceManager.GetString("BAD_ROW_MAMPARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La columna asociada no es válida para crear un tamaño de panel.
        /// </summary>
        internal static string BAD_ROW_PANEL {
            get {
                return ResourceManager.GetString("BAD_ROW_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atrás.
        /// </summary>
        internal static string CAPTION_BACK {
            get {
                return ResourceManager.GetString("CAPTION_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DaNTe.
        /// </summary>
        internal static string CAPTION_DAN {
            get {
                return ResourceManager.GetString("CAPTION_DAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al frente.
        /// </summary>
        internal static string CAPTION_FRONT {
            get {
                return ResourceManager.GetString("CAPTION_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ISMODULE.
        /// </summary>
        internal static string CAPTION_ISMODULE {
            get {
                return ResourceManager.GetString("CAPTION_ISMODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Izquierdo.
        /// </summary>
        internal static string CAPTION_LEFT {
            get {
                return ResourceManager.GetString("CAPTION_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En la izquierda por atrás.
        /// </summary>
        internal static string CAPTION_LEFT_BACK {
            get {
                return ResourceManager.GetString("CAPTION_LEFT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En la izquierda al frente.
        /// </summary>
        internal static string CAPTION_LEFT_FRONT {
            get {
                return ResourceManager.GetString("CAPTION_LEFT_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODULE_TMP.
        /// </summary>
        internal static string CAPTION_MODULE_RECORD {
            get {
                return ResourceManager.GetString("CAPTION_MODULE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODULE_TMP_3D.
        /// </summary>
        internal static string CAPTION_MODULE_RECORD3D {
            get {
                return ResourceManager.GetString("CAPTION_MODULE_RECORD3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin descripción.
        /// </summary>
        internal static string CAPTION_NO_DESC {
            get {
                return ResourceManager.GetString("CAPTION_NO_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuantificaciones.
        /// </summary>
        internal static string CAPTION_QUANTIFICATIONS {
            get {
                return ResourceManager.GetString("CAPTION_QUANTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Derecho.
        /// </summary>
        internal static string CAPTION_RIGHT {
            get {
                return ResourceManager.GetString("CAPTION_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En la derecha por atrás.
        /// </summary>
        internal static string CAPTION_RIGHT_BACK {
            get {
                return ResourceManager.GetString("CAPTION_RIGHT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En la derecha por atrás.
        /// </summary>
        internal static string CAPTION_RIGHT_FRONT {
            get {
                return ResourceManager.GetString("CAPTION_RIGHT_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona.
        /// </summary>
        internal static string CAPTION_ZONE {
            get {
                return ResourceManager.GetString("CAPTION_ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar un elemento en la parte superior de la mampara.
        ///Detalles: 
        ///{0}.
        /// </summary>
        internal static string ERR_ADD_BIOMBO {
            get {
                return ResourceManager.GetString("ERR_ADD_BIOMBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al leer la base de datos de asociados, no se a encontro el archivo &quot;{0}&quot;. Revise que el archivo no haya sido movido o borrado..
        /// </summary>
        internal static string ERR_ASOCIADOS_MDB_MISSING {
            get {
                return ResourceManager.GetString("ERR_ASOCIADOS_MDB_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al leer la base de datos de asociados, no se a definido ninguna base de asociados. Asociar una base en configuraciones..
        /// </summary>
        internal static string ERR_ASOCIADOS_MDB_NOT_DEFINED {
            get {
                return ResourceManager.GetString("ERR_ASOCIADOS_MDB_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede iniciar sesión con las credenciales proporcionadas..
        /// </summary>
        internal static string ERR_BAD_LOGIN {
            get {
                return ResourceManager.GetString("ERR_BAD_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión..
        /// </summary>
        internal static string ERR_CONN {
            get {
                return ResourceManager.GetString("ERR_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el bloque 3D para el panel {0}, Exc: {1}..
        /// </summary>
        internal static string ERR_CREATING_3D_PANEL {
            get {
                return ResourceManager.GetString("ERR_CREATING_3D_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El frente de las mamparas en la unión no está soportado para un panel doble.
        ///Usar mamparas con frentes de 18&quot; o de 24&quot;.
        /// </summary>
        internal static string ERR_FRENTE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_FRENTE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario o password son incorrectos.
        /// </summary>
        internal static string ERR_INVALID_USER_PASS {
            get {
                return ResourceManager.GetString("ERR_INVALID_USER_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo es posible seleccionar una unión en T..
        /// </summary>
        internal static string ERR_JUST_T {
            get {
                return ResourceManager.GetString("ERR_JUST_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede conectar a Oracle con la información proporcionada, todos los campos son obligatorios..
        /// </summary>
        internal static string ERR_ORACLE_CONN_MISSING {
            get {
                return ResourceManager.GetString("ERR_ORACLE_CONN_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se encontraron errores en la cuantificación. Los elementos con errores han sido resaltados.
        /// </summary>
        internal static string ERR_QERRORS {
            get {
                return ResourceManager.GetString("ERR_QERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede realizar una cuantificación si no se proporciona un nombre para la cuantificación.
        /// </summary>
        internal static string ERR_QNAME_NEEDED {
            get {
                return ResourceManager.GetString("ERR_QNAME_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los frentes de las mamparas adyacentes en la unión en T deben ser iguales..
        /// </summary>
        internal static string ERR_SAME_FRENTE {
            get {
                return ResourceManager.GetString("ERR_SAME_FRENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar el archivo de Access.
        /// </summary>
        internal static string ERR_SAV_ACCESS {
            get {
                return ResourceManager.GetString("ERR_SAV_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El panel electrificable quedaría del lado de 24&quot;, no es válido.
        ///Rote la mampara para poder continuar con la calificación..
        /// </summary>
        internal static string ERR_SOP_24IN {
            get {
                return ResourceManager.GetString("ERR_SOP_24IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconocido..
        /// </summary>
        internal static string ERR_UNKNOWN {
            get {
                return ResourceManager.GetString("ERR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string FIELD_BACK {
            get {
                return ResourceManager.GetString("FIELD_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        internal static string FIELD_CODE {
            get {
                return ResourceManager.GetString("FIELD_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DaNTe.
        /// </summary>
        internal static string FIELD_DIC_DANTE {
            get {
                return ResourceManager.GetString("FIELD_DIC_DANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disposable3DBlock.
        /// </summary>
        internal static string FIELD_DISPOSABLE_3D {
            get {
                return ResourceManager.GetString("FIELD_DISPOSABLE_3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End.
        /// </summary>
        internal static string FIELD_END {
            get {
                return ResourceManager.GetString("FIELD_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extra.
        /// </summary>
        internal static string FIELD_EXTRA {
            get {
                return ResourceManager.GetString("FIELD_EXTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Front.
        /// </summary>
        internal static string FIELD_FRONT {
            get {
                return ResourceManager.GetString("FIELD_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Geometry.
        /// </summary>
        internal static string FIELD_GEOMETRY {
            get {
                return ResourceManager.GetString("FIELD_GEOMETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left_Back.
        /// </summary>
        internal static string FIELD_LEFT_BACK {
            get {
                return ResourceManager.GetString("FIELD_LEFT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left_Front.
        /// </summary>
        internal static string FIELD_LEFT_FRONT {
            get {
                return ResourceManager.GetString("FIELD_LEFT_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parent.
        /// </summary>
        internal static string FIELD_PARENT {
            get {
                return ResourceManager.GetString("FIELD_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        internal static string FIELD_REG_ID {
            get {
                return ResourceManager.GetString("FIELD_REG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Units.
        /// </summary>
        internal static string FIELD_REG_UNITS {
            get {
                return ResourceManager.GetString("FIELD_REG_UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right_Back.
        /// </summary>
        internal static string FIELD_RIGHT_BACK {
            get {
                return ResourceManager.GetString("FIELD_RIGHT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right_Front.
        /// </summary>
        internal static string FIELD_RIGHT_FRONT {
            get {
                return ResourceManager.GetString("FIELD_RIGHT_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size.
        /// </summary>
        internal static string FIELD_SIZE {
            get {
                return ResourceManager.GetString("FIELD_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        internal static string FIELD_START {
            get {
                return ResourceManager.GetString("FIELD_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EnfasisMamparaReport.
        /// </summary>
        internal static string GROUP_MAM_REP {
            get {
                return ResourceManager.GetString("GROUP_MAM_REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DD2D_Error.
        /// </summary>
        internal static string LAYER_ERR {
            get {
                return ResourceManager.GetString("LAYER_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DD2D_Geometry.
        /// </summary>
        internal static string LAYER_RIVIERA_GEOMETRY {
            get {
                return ResourceManager.GetString("LAYER_RIVIERA_GEOMETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DD2D.
        /// </summary>
        internal static string LAYER_RIVIERA_OBJECT {
            get {
                return ResourceManager.GetString("LAYER_RIVIERA_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DDReportes.
        /// </summary>
        internal static string LAYER_RIVIERA_REPORT {
            get {
                return ResourceManager.GetString("LAYER_RIVIERA_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexión establecida..
        /// </summary>
        internal static string MSG_CONN {
            get {
                return ResourceManager.GetString("MSG_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generando la cuantificación al archivo mdb.
        /// </summary>
        internal static string MSG_DANTE_WORKING {
            get {
                return ResourceManager.GetString("MSG_DANTE_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agregó la mampara ({0}) en la posición {1}.
        ///.
        /// </summary>
        internal static string MSG_MAM_ADD {
            get {
                return ResourceManager.GetString("MSG_MAM_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado el directorio de módulos, especificarlo antes de crear el bloque..
        /// </summary>
        internal static string MSG_MODULE_DIR_MISSING {
            get {
                return ResourceManager.GetString("MSG_MODULE_DIR_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El elemento seleccionado no fue definido por la aplicación.
        ///.
        /// </summary>
        internal static string MSG_NOT_IN_DB {
            get {
                return ResourceManager.GetString("MSG_NOT_IN_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro de realizar la cuantificación en el proyecto {0}..
        /// </summary>
        internal static string MSG_ORACLE_Q {
            get {
                return ResourceManager.GetString("MSG_ORACLE_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño seleccionado es el mismo al asignado anteriormente, no hay cambios que aplicar.
        /// </summary>
        internal static string MSG_SAME_SIZE {
            get {
                return ResourceManager.GetString("MSG_SAME_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una unión en T para crear o editar un panel doble.
        ///El panel debe tener en la unión dos mamparas de 18&quot; o dos de 24&quot;..
        /// </summary>
        internal static string MSG_SEL_DOUBLE_PANEL {
            get {
                return ResourceManager.GetString("MSG_SEL_DOUBLE_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione las mamparas a reportar.
        /// </summary>
        internal static string MSG_SEL_MAM {
            get {
                return ResourceManager.GetString("MSG_SEL_MAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el punto de inserción para el reporte de las mamparas tipos.
        /// </summary>
        internal static string MSG_SEL_MAM_REP_TIPO {
            get {
                return ResourceManager.GetString("MSG_SEL_MAM_REP_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona las mamparas a las que se aplicará el estilo, solo son válidas las mamparas que tengan el mismo frente y misma altura.
        /// </summary>
        internal static string MSG_SEL_MAMPARA_TO_PASTE {
            get {
                return ResourceManager.GetString("MSG_SEL_MAMPARA_TO_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione los elementos que serán agregados al modulo.
        /// </summary>
        internal static string MSG_SEL_MOD {
            get {
                return ResourceManager.GetString("MSG_SEL_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un elemento para editar.
        /// </summary>
        internal static string MSG_SEL_OBJ {
            get {
                return ResourceManager.GetString("MSG_SEL_OBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona la mampara base para copiar su diseño de paneles..
        /// </summary>
        internal static string MSG_SEL_PANEL_SOURCE {
            get {
                return ResourceManager.GetString("MSG_SEL_PANEL_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione los elementos a eliminar.
        /// </summary>
        internal static string MSG_SEL_TO_DEL {
            get {
                return ResourceManager.GetString("MSG_SEL_TO_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesión iniciada como el usuario {0} en el proyecto {1}.
        /// </summary>
        internal static string MSG_SESS_INIT {
            get {
                return ResourceManager.GetString("MSG_SESS_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay ninguna mampara seleccionada, seleccione una para poder agregar un panel.
        ///Para seleccionar una mampara solo es necesario dar click en ella..
        /// </summary>
        internal static string MSG_STACK_NOT_SEL {
            get {
                return ResourceManager.GetString("MSG_STACK_NOT_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La transacción ha terminado.
        /// </summary>
        internal static string MSG_TRANSACTION_FINISHED {
            get {
                return ResourceManager.GetString("MSG_TRANSACTION_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SPACE_{0}.
        /// </summary>
        internal static string PREFIX_BLOCK {
            get {
                return ResourceManager.GetString("PREFIX_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una dirección..
        /// </summary>
        internal static string SEL_ARROW_DIR {
            get {
                return ResourceManager.GetString("SEL_ARROW_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACAD_ISO02W100.
        /// </summary>
        internal static string STYLE_DASHED_LINE {
            get {
                return ResourceManager.GetString("STYLE_DASHED_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UNIONTYPE.
        /// </summary>
        internal static string tea {
            get {
                return ResourceManager.GetString("tea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Cuantificación.
        /// </summary>
        internal static string TIT_EXPORT_QUAN {
            get {
                return ResourceManager.GetString("TIT_EXPORT_QUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar DaNTe MDB.
        /// </summary>
        internal static string TIT_SEL_DANTE {
            get {
                return ResourceManager.GetString("TIT_SEL_DANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los dos lados de la mampara deben estar completamente definidos, para continuar.
        /// </summary>
        internal static string WAR_INCOMPLETE_PANEL {
            get {
                return ResourceManager.GetString("WAR_INCOMPLETE_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los paneles de nivel intermedio solo pueden ser insertados al final de la mampara..
        /// </summary>
        internal static string WAR_MIDDLE_HEIGHT_P {
            get {
                return ResourceManager.GetString("WAR_MIDDLE_HEIGHT_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay suficiente espacio en la mampara seleccionada, par insertar el panel {0}..
        /// </summary>
        internal static string WAR_PAN_BAD_SIZE {
            get {
                return ResourceManager.GetString("WAR_PAN_BAD_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se permite tener más de un panel con nivel intermedios en la mampara..
        /// </summary>
        internal static string WAR_PAN_LAST_HALF {
            get {
                return ResourceManager.GetString("WAR_PAN_LAST_HALF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El panel {0} solo puede ser insertado a piso..
        /// </summary>
        internal static string WAR_PP {
            get {
                return ResourceManager.GetString("WAR_PP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe regla para la unión en {0}
        ///AM1_0: {1}, AM2_90: {2}, AM3_180: {3}, AM3_270: {4}.
        /// </summary>
        internal static string WAR_RULE_NOT_FOUND {
            get {
                return ResourceManager.GetString("WAR_RULE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe una restricción de nivel para el código {0}, no puede ser insertado en el Nivel {1}.
        /// </summary>
        internal static string WARNING_LEVEL_RULE {
            get {
                return ResourceManager.GetString("WARNING_LEVEL_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para poder crear un panel doble las mamparas deben ser del mismo tipo, frente y altura..
        /// </summary>
        internal static string WARNING_PDOBLE_DIFF {
            get {
                return ResourceManager.GetString("WARNING_PDOBLE_DIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para poder crear un panel doble las mamparas deben tener un frente de 18&quot; o 24&quot;..
        /// </summary>
        internal static string WARNING_PDOBLE_INVALID_FRONT {
            get {
                return ResourceManager.GetString("WARNING_PDOBLE_INVALID_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La aplicación no esta lista, ejecute primero el comando {0} para iniciar la aplicación..
        /// </summary>
        internal static string WARNING_START_CMD {
            get {
                return ResourceManager.GetString("WARNING_START_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen uniones en &quot;X&quot; con cuatro alturas diferentes. Estas alturas no son válidas para la unión en X..
        /// </summary>
        internal static string WARNING_X_BAD_UNION {
            get {
                return ResourceManager.GetString("WARNING_X_BAD_UNION", resourceCulture);
            }
        }
    }
}
