//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaSoft.Riviera.Modulador.Core.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaSoft.Riviera.Modulador.Core.Assets.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto &quot;{0}&quot; no existe. ¿Desea crearlo?.
        /// </summary>
        internal static string ASK_NEW_PROJECT {
            get {
                return ResourceManager.GetString("ASK_NEW_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna asociada no es válida para crear un tamaño de mampara.
        /// </summary>
        internal static string BAD_ROW_MAMPARA {
            get {
                return ResourceManager.GetString("BAD_ROW_MAMPARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna asociada no es válida para crear un tamaño de panel.
        /// </summary>
        internal static string BAD_ROW_PANEL {
            get {
                return ResourceManager.GetString("BAD_ROW_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando....
        /// </summary>
        internal static string CAP_LOADING {
            get {
                return ResourceManager.GetString("CAP_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrás.
        /// </summary>
        internal static string CAPTION_BACK {
            get {
                return ResourceManager.GetString("CAPTION_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaNTe.
        /// </summary>
        internal static string CAPTION_DAN {
            get {
                return ResourceManager.GetString("CAPTION_DAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al frente.
        /// </summary>
        internal static string CAPTION_FRONT {
            get {
                return ResourceManager.GetString("CAPTION_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISMODULE.
        /// </summary>
        internal static string CAPTION_ISMODULE {
            get {
                return ResourceManager.GetString("CAPTION_ISMODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izquierdo.
        /// </summary>
        internal static string CAPTION_LEFT {
            get {
                return ResourceManager.GetString("CAPTION_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En la izquierda por atrás.
        /// </summary>
        internal static string CAPTION_LEFT_BACK {
            get {
                return ResourceManager.GetString("CAPTION_LEFT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En la izquierda al frente.
        /// </summary>
        internal static string CAPTION_LEFT_FRONT {
            get {
                return ResourceManager.GetString("CAPTION_LEFT_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión.
        /// </summary>
        internal static string CAPTION_LOG_IN {
            get {
                return ResourceManager.GetString("CAPTION_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODULE_TMP.
        /// </summary>
        internal static string CAPTION_MODULE_RECORD {
            get {
                return ResourceManager.GetString("CAPTION_MODULE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODULE_TMP_3D.
        /// </summary>
        internal static string CAPTION_MODULE_RECORD3D {
            get {
                return ResourceManager.GetString("CAPTION_MODULE_RECORD3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin descripción.
        /// </summary>
        internal static string CAPTION_NO_DESC {
            get {
                return ResourceManager.GetString("CAPTION_NO_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuantificaciones.
        /// </summary>
        internal static string CAPTION_QUANTIFICATIONS {
            get {
                return ResourceManager.GetString("CAPTION_QUANTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derecho.
        /// </summary>
        internal static string CAPTION_RIGHT {
            get {
                return ResourceManager.GetString("CAPTION_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En la derecha por atrás.
        /// </summary>
        internal static string CAPTION_RIGHT_BACK {
            get {
                return ResourceManager.GetString("CAPTION_RIGHT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En la derecha por atrás.
        /// </summary>
        internal static string CAPTION_RIGHT_FRONT {
            get {
                return ResourceManager.GetString("CAPTION_RIGHT_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        internal static string CAPTION_ZONE {
            get {
                return ResourceManager.GetString("CAPTION_ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar un elemento en la parte superior de la mampara.
        ///Detalles: 
        ///{0}.
        /// </summary>
        internal static string ERR_ADD_BIOMBO {
            get {
                return ResourceManager.GetString("ERR_ADD_BIOMBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al leer la base de datos de asociados, no se a encontro el archivo &quot;{0}&quot;. Revise que el archivo no haya sido movido o borrado..
        /// </summary>
        internal static string ERR_ASOCIADOS_MDB_MISSING {
            get {
                return ResourceManager.GetString("ERR_ASOCIADOS_MDB_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al leer la base de datos de asociados, no se a definido ninguna base de asociados. Asociar una base en configuraciones..
        /// </summary>
        internal static string ERR_ASOCIADOS_MDB_NOT_DEFINED {
            get {
                return ResourceManager.GetString("ERR_ASOCIADOS_MDB_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede iniciar sesión con las credenciales proporcionadas..
        /// </summary>
        internal static string ERR_BAD_LOGIN {
            get {
                return ResourceManager.GetString("ERR_BAD_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de conexión..
        /// </summary>
        internal static string ERR_CONN {
            get {
                return ResourceManager.GetString("ERR_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear el bloque 3D para el panel {0}, Exc: {1}..
        /// </summary>
        internal static string ERR_CREATING_3D_PANEL {
            get {
                return ResourceManager.GetString("ERR_CREATING_3D_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El frente de las mamparas en la unión no está soportado para un panel doble.
        ///Usar mamparas con frentes de 18&quot; o de 24&quot;.
        /// </summary>
        internal static string ERR_FRENTE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_FRENTE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al leer el nombre del proyecto..
        /// </summary>
        internal static string ERR_GET_PRJ_NAME {
            get {
                return ResourceManager.GetString("ERR_GET_PRJ_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al inicializar la base de datos..
        /// </summary>
        internal static string ERR_INIT_DB {
            get {
                return ResourceManager.GetString("ERR_INIT_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear el proyecto &quot;{0}&quot;.
        ///Detalles: {1}.
        /// </summary>
        internal static string ERR_INS_PRJ {
            get {
                return ResourceManager.GetString("ERR_INS_PRJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario o password son incorrectos.
        /// </summary>
        internal static string ERR_INVALID_USER_PASS {
            get {
                return ResourceManager.GetString("ERR_INVALID_USER_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo es posible seleccionar una unión en T..
        /// </summary>
        internal static string ERR_JUST_T {
            get {
                return ResourceManager.GetString("ERR_JUST_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar los códigos de Riviera.
        /// </summary>
        internal static string ERR_LOAD_RIV_CODES {
            get {
                return ResourceManager.GetString("ERR_LOAD_RIV_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al iniciar sesión.
        /// </summary>
        internal static string ERR_LOGIN {
            get {
                return ResourceManager.GetString("ERR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede conectar a Oracle con la información proporcionada, todos los campos son obligatorios..
        /// </summary>
        internal static string ERR_ORACLE_CONN_MISSING {
            get {
                return ResourceManager.GetString("ERR_ORACLE_CONN_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encontraron errores en la cuantificación. Los elementos con errores han sido resaltados.
        /// </summary>
        internal static string ERR_QERRORS {
            get {
                return ResourceManager.GetString("ERR_QERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede realizar una cuantificación si no se proporciona un nombre para la cuantificación.
        /// </summary>
        internal static string ERR_QNAME_NEEDED {
            get {
                return ResourceManager.GetString("ERR_QNAME_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los frentes de las mamparas adyacentes en la unión en T deben ser iguales..
        /// </summary>
        internal static string ERR_SAME_FRENTE {
            get {
                return ResourceManager.GetString("ERR_SAME_FRENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar el archivo de Access.
        /// </summary>
        internal static string ERR_SAV_ACCESS {
            get {
                return ResourceManager.GetString("ERR_SAV_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El panel electrificable quedaría del lado de 24&quot;, no es válido.
        ///Rote la mampara para poder continuar con la calificación..
        /// </summary>
        internal static string ERR_SOP_24IN {
            get {
                return ResourceManager.GetString("ERR_SOP_24IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconocido..
        /// </summary>
        internal static string ERR_UNKNOWN {
            get {
                return ResourceManager.GetString("ERR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string FIELD_BACK {
            get {
                return ResourceManager.GetString("FIELD_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string FIELD_CODE {
            get {
                return ResourceManager.GetString("FIELD_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaNTe.
        /// </summary>
        internal static string FIELD_DIC_DANTE {
            get {
                return ResourceManager.GetString("FIELD_DIC_DANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposable3DBlock.
        /// </summary>
        internal static string FIELD_DISPOSABLE_3D {
            get {
                return ResourceManager.GetString("FIELD_DISPOSABLE_3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string FIELD_END {
            get {
                return ResourceManager.GetString("FIELD_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        internal static string FIELD_EXTRA {
            get {
                return ResourceManager.GetString("FIELD_EXTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        internal static string FIELD_FRONT {
            get {
                return ResourceManager.GetString("FIELD_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        internal static string FIELD_GEOMETRY {
            get {
                return ResourceManager.GetString("FIELD_GEOMETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left_Back.
        /// </summary>
        internal static string FIELD_LEFT_BACK {
            get {
                return ResourceManager.GetString("FIELD_LEFT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left_Front.
        /// </summary>
        internal static string FIELD_LEFT_FRONT {
            get {
                return ResourceManager.GetString("FIELD_LEFT_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string FIELD_PARENT {
            get {
                return ResourceManager.GetString("FIELD_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string FIELD_REG_ID {
            get {
                return ResourceManager.GetString("FIELD_REG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string FIELD_REG_UNITS {
            get {
                return ResourceManager.GetString("FIELD_REG_UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right_Back.
        /// </summary>
        internal static string FIELD_RIGHT_BACK {
            get {
                return ResourceManager.GetString("FIELD_RIGHT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right_Front.
        /// </summary>
        internal static string FIELD_RIGHT_FRONT {
            get {
                return ResourceManager.GetString("FIELD_RIGHT_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string FIELD_SIZE {
            get {
                return ResourceManager.GetString("FIELD_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string FIELD_START {
            get {
                return ResourceManager.GetString("FIELD_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnfasisMamparaReport.
        /// </summary>
        internal static string GROUP_MAM_REP {
            get {
                return ResourceManager.GetString("GROUP_MAM_REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexión establecida..
        /// </summary>
        internal static string MSG_CONN {
            get {
                return ResourceManager.GetString("MSG_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectando a la BD.
        /// </summary>
        internal static string MSG_CONNECTING {
            get {
                return ResourceManager.GetString("MSG_CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generando la cuantificación al archivo mdb.
        /// </summary>
        internal static string MSG_DANTE_WORKING {
            get {
                return ResourceManager.GetString("MSG_DANTE_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando datos desde la BD..
        /// </summary>
        internal static string MSG_LOADING_DB {
            get {
                return ResourceManager.GetString("MSG_LOADING_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando sesión como el usuario {0}..
        /// </summary>
        internal static string MSG_LOGGIN_IN {
            get {
                return ResourceManager.GetString("MSG_LOGGIN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó la mampara ({0}) en la posición {1}.
        ///.
        /// </summary>
        internal static string MSG_MAM_ADD {
            get {
                return ResourceManager.GetString("MSG_MAM_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memoria cargada en la aplicación.
        /// </summary>
        internal static string MSG_MEMORY_LOADED {
            get {
                return ResourceManager.GetString("MSG_MEMORY_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha especificado el directorio de módulos, especificarlo antes de crear el bloque..
        /// </summary>
        internal static string MSG_MODULE_DIR_MISSING {
            get {
                return ResourceManager.GetString("MSG_MODULE_DIR_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El elemento seleccionado no fue definido por la aplicación.
        ///.
        /// </summary>
        internal static string MSG_NOT_IN_DB {
            get {
                return ResourceManager.GetString("MSG_NOT_IN_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro de realizar la cuantificación en el proyecto {0}..
        /// </summary>
        internal static string MSG_ORACLE_Q {
            get {
                return ResourceManager.GetString("MSG_ORACLE_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el directorio de asociados..
        /// </summary>
        internal static string MSG_PICK_ASOC_DIR {
            get {
                return ResourceManager.GetString("MSG_PICK_ASOC_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el directorio de módulos..
        /// </summary>
        internal static string MSG_PICK_MOD_DIR {
            get {
                return ResourceManager.GetString("MSG_PICK_MOD_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño seleccionado es el mismo al asignado anteriormente, no hay cambios que aplicar.
        /// </summary>
        internal static string MSG_SAME_SIZE {
            get {
                return ResourceManager.GetString("MSG_SAME_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona una unión en T para crear o editar un panel doble.
        ///El panel debe tener en la unión dos mamparas de 18&quot; o dos de 24&quot;..
        /// </summary>
        internal static string MSG_SEL_DOUBLE_PANEL {
            get {
                return ResourceManager.GetString("MSG_SEL_DOUBLE_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione las mamparas a reportar.
        /// </summary>
        internal static string MSG_SEL_MAM {
            get {
                return ResourceManager.GetString("MSG_SEL_MAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el punto de inserción para el reporte de las mamparas tipos.
        /// </summary>
        internal static string MSG_SEL_MAM_REP_TIPO {
            get {
                return ResourceManager.GetString("MSG_SEL_MAM_REP_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona las mamparas a las que se aplicará el estilo, solo son válidas las mamparas que tengan el mismo frente y misma altura.
        /// </summary>
        internal static string MSG_SEL_MAMPARA_TO_PASTE {
            get {
                return ResourceManager.GetString("MSG_SEL_MAMPARA_TO_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione los elementos que serán agregados al modulo.
        /// </summary>
        internal static string MSG_SEL_MOD {
            get {
                return ResourceManager.GetString("MSG_SEL_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un elemento para editar.
        /// </summary>
        internal static string MSG_SEL_OBJ {
            get {
                return ResourceManager.GetString("MSG_SEL_OBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la mampara base para copiar su diseño de paneles..
        /// </summary>
        internal static string MSG_SEL_PANEL_SOURCE {
            get {
                return ResourceManager.GetString("MSG_SEL_PANEL_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione los elementos a eliminar.
        /// </summary>
        internal static string MSG_SEL_TO_DEL {
            get {
                return ResourceManager.GetString("MSG_SEL_TO_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión iniciada como el usuario {0} en el proyecto {1}.
        /// </summary>
        internal static string MSG_SESS_INIT {
            get {
                return ResourceManager.GetString("MSG_SESS_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ninguna mampara seleccionada, seleccione una para poder agregar un panel.
        ///Para seleccionar una mampara solo es necesario dar click en ella..
        /// </summary>
        internal static string MSG_STACK_NOT_SEL {
            get {
                return ResourceManager.GetString("MSG_STACK_NOT_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La transacción ha terminado.
        /// </summary>
        internal static string MSG_TRANSACTION_FINISHED {
            get {
                return ResourceManager.GetString("MSG_TRANSACTION_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPACE_{0}.
        /// </summary>
        internal static string PREFIX_BLOCK {
            get {
                return ResourceManager.GetString("PREFIX_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona una dirección..
        /// </summary>
        internal static string SEL_ARROW_DIR {
            get {
                return ResourceManager.GetString("SEL_ARROW_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACAD_ISO02W100.
        /// </summary>
        internal static string STYLE_DASHED_LINE {
            get {
                return ResourceManager.GetString("STYLE_DASHED_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIONTYPE.
        /// </summary>
        internal static string tea {
            get {
                return ResourceManager.GetString("tea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Cuantificación.
        /// </summary>
        internal static string TIT_EXPORT_QUAN {
            get {
                return ResourceManager.GetString("TIT_EXPORT_QUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexión a Oracle.
        /// </summary>
        internal static string TIT_ORACLE_CONN {
            get {
                return ResourceManager.GetString("TIT_ORACLE_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar DaNTe MDB.
        /// </summary>
        internal static string TIT_SEL_DANTE {
            get {
                return ResourceManager.GetString("TIT_SEL_DANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los dos lados de la mampara deben estar completamente definidos, para continuar.
        /// </summary>
        internal static string WAR_INCOMPLETE_PANEL {
            get {
                return ResourceManager.GetString("WAR_INCOMPLETE_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los paneles de nivel intermedio solo pueden ser insertados al final de la mampara..
        /// </summary>
        internal static string WAR_MIDDLE_HEIGHT_P {
            get {
                return ResourceManager.GetString("WAR_MIDDLE_HEIGHT_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay suficiente espacio en la mampara seleccionada, par insertar el panel {0}..
        /// </summary>
        internal static string WAR_PAN_BAD_SIZE {
            get {
                return ResourceManager.GetString("WAR_PAN_BAD_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se permite tener más de un panel con nivel intermedios en la mampara..
        /// </summary>
        internal static string WAR_PAN_LAST_HALF {
            get {
                return ResourceManager.GetString("WAR_PAN_LAST_HALF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El panel {0} solo puede ser insertado a piso..
        /// </summary>
        internal static string WAR_PP {
            get {
                return ResourceManager.GetString("WAR_PP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe regla para la unión en {0}
        ///AM1_0: {1}, AM2_90: {2}, AM3_180: {3}, AM3_270: {4}.
        /// </summary>
        internal static string WAR_RULE_NOT_FOUND {
            get {
                return ResourceManager.GetString("WAR_RULE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La aplicación no esta lista, ejecute primero el comando {0} para iniciar la aplicación..
        /// </summary>
        internal static string WAR_START_CMD {
            get {
                return ResourceManager.GetString("WAR_START_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe una restricción de nivel para el código {0}, no puede ser insertado en el Nivel {1}.
        /// </summary>
        internal static string WARNING_LEVEL_RULE {
            get {
                return ResourceManager.GetString("WARNING_LEVEL_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder crear un panel doble las mamparas deben ser del mismo tipo, frente y altura..
        /// </summary>
        internal static string WARNING_PDOBLE_DIFF {
            get {
                return ResourceManager.GetString("WARNING_PDOBLE_DIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder crear un panel doble las mamparas deben tener un frente de 18&quot; o 24&quot;..
        /// </summary>
        internal static string WARNING_PDOBLE_INVALID_FRONT {
            get {
                return ResourceManager.GetString("WARNING_PDOBLE_INVALID_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen uniones en &quot;X&quot; con cuatro alturas diferentes. Estas alturas no son válidas para la unión en X..
        /// </summary>
        internal static string WARNING_X_BAD_UNION {
            get {
                return ResourceManager.GetString("WARNING_X_BAD_UNION", resourceCulture);
            }
        }
    }
}
