//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamelessOld.Libraries.HoukagoTeaTime.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NamelessOld.Libraries.HoukagoTeaTime.Assets.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary entry key has an invalid name..
        /// </summary>
        internal static string BadDictionaryKey {
            get {
                return ResourceManager.GetString("BadDictionaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id is not valid..
        /// </summary>
        internal static string BadId {
            get {
                return ResourceManager.GetString("BadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of tabs must be equally to the number of controsl, add more strings to the Tabs property or remove strings, to match the controls size..
        /// </summary>
        internal static string BadTabSize {
            get {
                return ResourceManager.GetString("BadTabSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given value doesn&apos;t satisfy the current equation, .
        /// </summary>
        internal static string BadValueforLine {
            get {
                return ResourceManager.GetString("BadValueforLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dwg file doesn&apos;t exist, check the filepath: .
        /// </summary>
        internal static string BlockFileMissing {
            get {
                return ResourceManager.GetString("BlockFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not insert the block, the block is missing. Undefined,.
        /// </summary>
        internal static string BlockNameMissing {
            get {
                return ResourceManager.GetString("BlockNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name {0} does not exists in the block table record.
        /// </summary>
        internal static string BlockTableRecordMissing {
            get {
                return ResourceManager.GetString("BlockTableRecordMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected DbObject can not be erased..
        /// </summary>
        internal static string CanNotBeErased {
            get {
                return ResourceManager.GetString("CanNotBeErased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object can not be move to the layer {0}..
        /// </summary>
        internal static string CanNotBeMovedToLayer {
            get {
                return ResourceManager.GetString("CanNotBeMovedToLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more element can not be summoned as an entity..
        /// </summary>
        internal static string CanNotBeSummonedAsEntity {
            get {
                return ResourceManager.GetString("CanNotBeSummonedAsEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error doing the casting beetween entities..
        /// </summary>
        internal static string CanNotCastAnEntity {
            get {
                return ResourceManager.GetString("CanNotCastAnEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected polyline couldn&apos;t be close..
        /// </summary>
        internal static string CanNotClosePolyline {
            get {
                return ResourceManager.GetString("CanNotClosePolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The block can not be created.
        /// </summary>
        internal static string CanNotCreateBlock {
            get {
                return ResourceManager.GetString("CanNotCreateBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layer can&apos;t be created.
        /// </summary>
        internal static string CanNotCreateLayer {
            get {
                return ResourceManager.GetString("CanNotCreateLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity couldn&apos;t be draw..
        /// </summary>
        internal static string CanNotDraw {
            get {
                return ResourceManager.GetString("CanNotDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not extract the attribute value..
        /// </summary>
        internal static string CanNotExtractAttributeValue {
            get {
                return ResourceManager.GetString("CanNotExtractAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polyline can not be flipped..
        /// </summary>
        internal static string CanNotFlipPl {
            get {
                return ResourceManager.GetString("CanNotFlipPl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get the entity..
        /// </summary>
        internal static string CanNotSummonAnEntity {
            get {
                return ResourceManager.GetString("CanNotSummonAnEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get the object..
        /// </summary>
        internal static string CanNotSummonAnObject {
            get {
                return ResourceManager.GetString("CanNotSummonAnObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not update the entity properties..
        /// </summary>
        internal static string CanNotUpdateProperty {
            get {
                return ResourceManager.GetString("CanNotUpdateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating the polyline geometry.
        /// </summary>
        internal static string CreatingPolylineGeometry {
            get {
                return ResourceManager.GetString("CreatingPolylineGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity can not be tagged.
        /// </summary>
        internal static string EntityCanNotBeTagged {
            get {
                return ResourceManager.GetString("EntityCanNotBeTagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more entities can not be transform.
        /// </summary>
        internal static string EntityCanNotBeTransform {
            get {
                return ResourceManager.GetString("EntityCanNotBeTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The typed values failed to be added to an XRecord..
        /// </summary>
        internal static string ErrorAddingTypedValues {
            get {
                return ResourceManager.GetString("ErrorAddingTypedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create a new dictionary..
        /// </summary>
        internal static string ErrorCreatingDictionary {
            get {
                return ResourceManager.GetString("ErrorCreatingDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create a extension dictionary..
        /// </summary>
        internal static string ErrorCreatingExtensionDictionary {
            get {
                return ResourceManager.GetString("ErrorCreatingExtensionDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create a new XRecord..
        /// </summary>
        internal static string ErrorCreatingXRecord {
            get {
                return ResourceManager.GetString("ErrorCreatingXRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to define the initial state of the pulse generator automata..
        /// </summary>
        internal static string ErrorDefieneS0PulseWave {
            get {
                return ResourceManager.GetString("ErrorDefieneS0PulseWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to define the state s1 of the pulse generator automata..
        /// </summary>
        internal static string ErrorDefieneS1PulseWave {
            get {
                return ResourceManager.GetString("ErrorDefieneS1PulseWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to define the state s2 of the pulse generator automata..
        /// </summary>
        internal static string ErrorDefieneS2PulseWave {
            get {
                return ResourceManager.GetString("ErrorDefieneS2PulseWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to release the extension dictionary of the application..
        /// </summary>
        internal static string ErrorDestroyingExtDictionary {
            get {
                return ResourceManager.GetString("ErrorDestroyingExtDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to extract the string parameters..
        /// </summary>
        internal static string ErrorExtractingParamValue {
            get {
                return ResourceManager.GetString("ErrorExtractingParamValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to insert the block reference..
        /// </summary>
        internal static string ErrorInsertingBlockReference {
            get {
                return ResourceManager.GetString("ErrorInsertingBlockReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to read the Dictionary, be sure that the dictionary exists before trying to read it..
        /// </summary>
        internal static string ErrorReadingDictionary {
            get {
                return ResourceManager.GetString("ErrorReadingDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to read the XData information.
        /// </summary>
        internal static string ErrorReadingXData {
            get {
                return ResourceManager.GetString("ErrorReadingXData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to read the XRecord, be sure that the XRecord exists before trying to read it..
        /// </summary>
        internal static string ErrorReadingXrecord {
            get {
                return ResourceManager.GetString("ErrorReadingXrecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error found, in the error message..
        /// </summary>
        internal static string ErrorStateMsg {
            get {
                return ResourceManager.GetString("ErrorStateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension dictionary is now avaible for the entity with Handle, .
        /// </summary>
        internal static string ExtDictionaryCreated {
            get {
                return ResourceManager.GetString("ExtDictionaryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension dictionary was released from the current entity..
        /// </summary>
        internal static string ExtensionDictionaryIsReleased {
            get {
                return ResourceManager.GetString("ExtensionDictionaryIsReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the current layer..
        /// </summary>
        internal static string FailedGetCurrentLayer {
            get {
                return ResourceManager.GetString("FailedGetCurrentLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to select the layer as current one..
        /// </summary>
        internal static string FailedSetCurrentLayer {
            get {
                return ResourceManager.GetString("FailedSetCurrentLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the layer color..
        /// </summary>
        internal static string FailedToGetLayerColor {
            get {
                return ResourceManager.GetString("FailedToGetLayerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the layer status.
        /// </summary>
        internal static string FailedToGetLayerStatus {
            get {
                return ResourceManager.GetString("FailedToGetLayerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to list the layers of the current drawing..
        /// </summary>
        internal static string FailedToListLayers {
            get {
                return ResourceManager.GetString("FailedToListLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error transforming the entity.
        /// </summary>
        internal static string FailedToTransform {
            get {
                return ResourceManager.GetString("FailedToTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the freeze status of the selected layers..
        /// </summary>
        internal static string FailedToUpdateFreezeStatus {
            get {
                return ResourceManager.GetString("FailedToUpdateFreezeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the hidden status of the selected layers..
        /// </summary>
        internal static string FailedToUpdateHiddenStatus {
            get {
                return ResourceManager.GetString("FailedToUpdateHiddenStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update an entity layer.
        /// </summary>
        internal static string FailedToUpdateLayer {
            get {
                return ResourceManager.GetString("FailedToUpdateLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the lock status of the selected layers..
        /// </summary>
        internal static string FailedToUpdateLockStatus {
            get {
                return ResourceManager.GetString("FailedToUpdateLockStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the status of the layers..
        /// </summary>
        internal static string FailedToUpdateStatus {
            get {
                return ResourceManager.GetString("FailedToUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at run the command.
        /// </summary>
        internal static string ImposibleToRunCMD {
            get {
                return ResourceManager.GetString("ImposibleToRunCMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layer name is empty or is invalid, the layer name must not include the following characters:
        ///&lt;&gt;\&quot;:;?|,=&apos;`.
        /// </summary>
        internal static string InvalidLayerName {
            get {
                return ResourceManager.GetString("InvalidLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid point comparation.
        /// </summary>
        internal static string InvalidPointComparation {
            get {
                return ResourceManager.GetString("InvalidPointComparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of elements are not valid to create a region..
        /// </summary>
        internal static string InvalidRegionElements {
            get {
                return ResourceManager.GetString("InvalidRegionElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 2d line is not supported for the Z-axis.
        /// </summary>
        internal static string Line2dNotZSupported {
            get {
                return ResourceManager.GetString("Line2dNotZSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data has been added or updated to the XData of the entity.
        /// </summary>
        internal static string NewDataAddedXData {
            get {
                return ResourceManager.GetString("NewDataAddedXData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data has been added or updated to the XRecord..
        /// </summary>
        internal static string NewDataAddedXrecord {
            get {
                return ResourceManager.GetString("NewDataAddedXrecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new dictionary is created named,  .
        /// </summary>
        internal static string NewDictionaryAdded {
            get {
                return ResourceManager.GetString("NewDictionaryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new RegApp Record is created in the RegAppTable.
        /// </summary>
        internal static string NewRegAppRecord {
            get {
                return ResourceManager.GetString("NewRegAppRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new xRecord is created named, .
        /// </summary>
        internal static string NewXRecordAdded {
            get {
                return ResourceManager.GetString("NewXRecordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element is not a DBDictionary.
        /// </summary>
        internal static string NotADictionary {
            get {
                return ResourceManager.GetString("NotADictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element is not an entity..
        /// </summary>
        internal static string NotAnEntity {
            get {
                return ResourceManager.GetString("NotAnEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given value is not a segment..
        /// </summary>
        internal static string NotASegment {
            get {
                return ResourceManager.GetString("NotASegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element is not a XRecord.
        /// </summary>
        internal static string NotAXRecord {
            get {
                return ResourceManager.GetString("NotAXRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected entity doesn&apos;t match the requested type, select an entity of the following type:.
        /// </summary>
        internal static string NotCorrectData {
            get {
                return ResourceManager.GetString("NotCorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected polyline doesn&apos;t contains a pulse wave geometry. A pulse is made of segments, each segment has the same size and has only straight angles..
        /// </summary>
        internal static string PolylineIsNotAPulse {
            get {
                return ResourceManager.GetString("PolylineIsNotAPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Reading Block Table Record..
        /// </summary>
        internal static string ReadingBlockTable {
            get {
                return ResourceManager.GetString("ReadingBlockTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to remove the dictionary..
        /// </summary>
        internal static string RemovingDictionary {
            get {
                return ResourceManager.GetString("RemovingDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to remove the XRecord..
        /// </summary>
        internal static string RemovingXRecord {
            get {
                return ResourceManager.GetString("RemovingXRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selection type is not supported..
        /// </summary>
        internal static string SelectionTypeNotSupported {
            get {
                return ResourceManager.GetString("SelectionTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la transacción.
        /// </summary>
        internal static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given value is out of the bounds of the segment..
        /// </summary>
        internal static string ValueIsOutOfSegment {
            get {
                return ResourceManager.GetString("ValueIsOutOfSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error veryfing the existance of the dictionary..
        /// </summary>
        internal static string VerifyingExistance {
            get {
                return ResourceManager.GetString("VerifyingExistance", resourceCulture);
            }
        }
    }
}
