  CREATE TABLE "RIVIERA"."BR_COD_FREN_FON_ALT_PUE" 
   (	"CODIGO" VARCHAR2(20 BYTE), 
	"FRENTE" NUMBER, 
	"FONDO" NUMBER, 
	"ALTO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "RIVIERA" ;