  CREATE TABLE "RIVIERA"."BR_COD_FREN_ALT_PAN" 
   ( "CODIGO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FRENTE" NUMBER, 
	"ALTO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "RIVIERA" ;