--------------------------------------------------------
-- Archivo creado  - miércoles-mayo-17-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COD_ASOCIADOS
--------------------------------------------------------

  CREATE TABLE "RIVIERA"."COD_ASOCIADOS" 
   (	"CODIGO_DANTE" VARCHAR2(30 BYTE), 
	"CODIGO_ASOCIADO" VARCHAR2(30 BYTE), 
	"CANTIDAD" NUMBER(7,0), 
	"LARGO" NUMBER(5,0), 
	"ANCHO" NUMBER(5,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RIVIERA" ;
REM INSERTING into RIVIERA.COD_ASOCIADOS
SET DEFINE OFF;
Insert into RIVIERA.COD_ASOCIADOS (CODIGO_DANTE,CODIGO_ASOCIADO,CANTIDAD,LARGO,ANCHO) values ('230FFL','MMSD','1',null,null);
Insert into RIVIERA.COD_ASOCIADOS (CODIGO_DANTE,CODIGO_ASOCIADO,CANTIDAD,LARGO,ANCHO) values ('CHBAR01','CHM01','1','1','1');
Insert into RIVIERA.COD_ASOCIADOS (CODIGO_DANTE,CODIGO_ASOCIADO,CANTIDAD,LARGO,ANCHO) values ('CHBAR01','BAR01','1','1','1');
Insert into RIVIERA.COD_ASOCIADOS (CODIGO_DANTE,CODIGO_ASOCIADO,CANTIDAD,LARGO,ANCHO) values ('COM01','MDF19','2','1','2');
Insert into RIVIERA.COD_ASOCIADOS (CODIGO_DANTE,CODIGO_ASOCIADO,CANTIDAD,LARGO,ANCHO) values ('COM02','MDF19','22','1','1');
