--------------------------------------------------------
-- Archivo creado  - miércoles-agosto-17-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DT_COD_RULES_PAN
--------------------------------------------------------

  CREATE TABLE "RIVIERA"."DT_COD_RULES_PAN" 
   (	"CODIGO" VARCHAR2(15 BYTE), 
	"NIVEL1" VARCHAR2(1 BYTE), 
	"NIVEL2" VARCHAR2(1 BYTE), 
	"NIVEL3" VARCHAR2(1 BYTE), 
	"NIVEL4" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RIVIERA" ;
REM INSERTING into RIVIERA.DT_COD_RULES_PAN
SET DEFINE OFF;
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2011','Y','Y','Y','Y');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2012','Y','Y','Y','Y');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2013','Y','Y','Y','Y');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2015','Y','Y','Y','Y');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2016','N','N','Y','Y');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2017','N','N','Y','Y');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2031','N','Y','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2032','N','Y','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2033','N','Y','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2035','N','Y','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2036','N','Y','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2037','N','Y','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2040','N','N','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2041','N','N','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2042','N','N','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2043','N','N','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2044','N','N','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2045','N','N','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2046','N','N','Y','N');
Insert into RIVIERA.DT_COD_RULES_PAN (CODIGO,NIVEL1,NIVEL2,NIVEL3,NIVEL4) values ('DD2047','N','N','Y','N');
--------------------------------------------------------
--  Constraints for Table DT_COD_RULES_PAN
--------------------------------------------------------

  ALTER TABLE "RIVIERA"."DT_COD_RULES_PAN" MODIFY ("CODIGO" NOT NULL ENABLE);
