--------------------------------------------------------
-- Archivo creado  - miércoles-agosto-17-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DT_COD_FREN_ALT_MAM
--------------------------------------------------------

  CREATE TABLE "RIVIERA"."DT_COD_FREN_ALT_MAM" 
   (	"CODIGO" VARCHAR2(15 BYTE), 
	"FRENTE" NUMBER, 
	"ALTO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RIVIERA" ;
REM INSERTING into RIVIERA.DT_COD_FREN_ALT_MAM
SET DEFINE OFF;
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',18,30);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',18,36);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',18,42);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',24,30);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',24,36);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',24,42);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',24,48);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',24,54);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',30,30);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',30,36);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',30,42);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',30,48);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',30,54);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',36,30);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',36,36);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',36,42);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',36,48);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',36,54);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',42,30);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',42,36);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',42,42);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',42,48);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',42,54);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',48,30);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',48,36);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',48,42);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',48,48);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',48,54);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',54,30);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',54,36);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',54,42);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',54,48);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',54,54);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',60,30);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',60,36);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',60,42);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',60,48);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',60,54);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',66,30);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',66,36);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',66,42);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',72,30);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',72,36);
Insert into RIVIERA.DT_COD_FREN_ALT_MAM (CODIGO,FRENTE,ALTO) values ('DD1010',72,42);
--------------------------------------------------------
--  Constraints for Table DT_COD_FREN_ALT_MAM
--------------------------------------------------------

  ALTER TABLE "RIVIERA"."DT_COD_FREN_ALT_MAM" MODIFY ("CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "RIVIERA"."DT_COD_FREN_ALT_MAM" MODIFY ("FRENTE" NOT NULL ENABLE);
 
  ALTER TABLE "RIVIERA"."DT_COD_FREN_ALT_MAM" MODIFY ("ALTO" NOT NULL ENABLE);
