  CREATE TABLE "RIVIERA"."DT_COD_ACAB" 
   (	"CODIGO" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"ACBADO" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(30 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RIVIERA" ;