--------------------------------------------------------
-- Archivo creado  - miércoles-agosto-17-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DT_FREN_ALT_MAM
--------------------------------------------------------

  CREATE TABLE "RIVIERA"."DT_FREN_ALT_MAM" 
   (	"VNOMINAL" NUMBER, 
	"VREAL" NUMBER, 
	"TIPO" VARCHAR2(2 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "RIVIERA" ;
REM INSERTING into RIVIERA.DT_FREN_ALT_MAM
SET DEFINE OFF;
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (24,600,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (30,752,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (36,905,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (42,1057,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (48,1210,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (54,1362,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (60,1514,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (66,1666,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (72,1820,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (18,447,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (40,986,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (52,1292,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (6,146,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (12,299,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (18,451,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (24,604,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (30,756,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (36,909,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (42,1061,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (5,124,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (11,273,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (17,426,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (23,579,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (29,731,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (35,884,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (41,1036,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (47,1188,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (53,1342,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (14,351,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (3030,1514,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (3036,1666,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (3630,1666,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (3636,1820,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (2430,1362,'FG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (8,198,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (20,503,'AG');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (18,457,'FM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (24,610,'FM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (30,762,'FM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (36,915,'FM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (42,1067,'FM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (48,1220,'FM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (54,1372,'FM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (60,1524,'FM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (66,1676,'FM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (72,1830,'FM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (30,738,'AM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (36,891,'AM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (42,1043,'AM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (48,1196,'AM');
Insert into RIVIERA.DT_FREN_ALT_MAM (VNOMINAL,VREAL,TIPO) values (54,1348,'AM');
--------------------------------------------------------
--  Constraints for Table DT_FREN_ALT_MAM
--------------------------------------------------------

  ALTER TABLE "RIVIERA"."DT_FREN_ALT_MAM" MODIFY ("VNOMINAL" NOT NULL ENABLE);
 
  ALTER TABLE "RIVIERA"."DT_FREN_ALT_MAM" MODIFY ("VREAL" NOT NULL ENABLE);
 
  ALTER TABLE "RIVIERA"."DT_FREN_ALT_MAM" MODIFY ("TIPO" NOT NULL ENABLE);
