SELECT
  FRE.CODIGO,
  FRE.FRENTE_NOMINAL,
  FRE.FRENTE_REAL_M,
  FON.FONDO_NOMINAL,
  FON.FONDO_REAL_M,
  ALT.ALTO_NOMINAL,
  ALT.ALTO_REAL_M
FROM
(SELECT
  DISTINCT(CODIGO||FRENTE) AS FKEY,
    CODIGO,
    FRENTE AS FRENTE_NOMINAL,
    VREAL/1000 AS FRENTE_REAL_M
  FROM 
    BR_COD_FREN_FON_ALT_PUE PUE, 
    BR_TAMANOS TAM 
  WHERE 
    PUE.FRENTE=TAM.VNOMINAL 
  AND 
    TAM.TIPO = 'FPU') FRE,
  (SELECT
  DISTINCT(CODIGO||FONDO) AS FOKEY,
    CODIGO,
    FONDO AS FONDO_NOMINAL,
    VREAL/1000 AS FONDO_REAL_M
  FROM 
    BR_COD_FREN_FON_ALT_PUE PUE, 
    BR_TAMANOS TAM 
  WHERE 
    PUE.FONDO=TAM.VNOMINAL 
  AND 
    TAM.TIPO = 'FOP') FON,
(SELECT
  DISTINCT(CODIGO||ALTO) AS FOKEY,
    CODIGO,
    ALTO AS ALTO_NOMINAL,
    VREAL/1000 AS ALTO_REAL_M
  FROM 
    BR_COD_FREN_FON_ALT_PUE PUE, 
    BR_TAMANOS TAM 
  WHERE 
    PUE.ALTO=TAM.VNOMINAL 
  AND 
    TAM.TIPO = 'APU') ALT
WHERE
	FRE.CODIGO = FON.CODIGO 
	AND
	FON.CODIGO = ALT.CODIGO
ORDER BY FRE.CODIGO, FRE.FRENTE_NOMINAL, FON.FONDO_NOMINAL, ALT.ALTO_NOMINAL